"""Reusable Multiwfn runtime and operation-level automation contracts."""

from .adapter import (
    MultiwfnAdapterError,
    MultiwfnCommandSpec,
    MultiwfnOutputSpec,
    build_command_spec,
    discover_outputs,
)
from .excited_states import (
    DPrecisionValidation,
    DeferredFragmentAnalysisError,
    Multiwfn38HoleElectronRenderer,
    Multiwfn38NtoRenderer,
    MultiwfnExcitedStateError,
    MultiwfnFinalizationError,
    MultiwfnSessionParseError,
    MultiwfnStateIdentityError,
    NtoPairRecord,
    NtoPairSelection,
    ParsedMultiwfnHoleElectron,
    ParsedMultiwfnNto,
    RenderedMultiwfnExcitedStateInput,
    UnsupportedMultiwfnFormatError,
    build_excited_state_command_spec,
    finalize_multiwfn_hole_electron_artifact,
    finalize_multiwfn_nto_artifact,
    parse_multiwfn38_hole_electron_session,
    parse_multiwfn38_hole_electron_session_file,
    parse_multiwfn38_nto_session,
    parse_multiwfn38_nto_session_file,
    select_nto_pairs_for_cumulative_cutoff,
    validate_reported_D_precision,
)
from .runtime import DEFAULT_MULTIWFN_NTHREADS, MultiwfnRuntime

__all__ = [
    "DEFAULT_MULTIWFN_NTHREADS",
    "DPrecisionValidation",
    "DeferredFragmentAnalysisError",
    "MultiwfnAdapterError",
    "Multiwfn38HoleElectronRenderer",
    "Multiwfn38NtoRenderer",
    "MultiwfnCommandSpec",
    "MultiwfnExcitedStateError",
    "MultiwfnFinalizationError",
    "MultiwfnOutputSpec",
    "MultiwfnRuntime",
    "MultiwfnSessionParseError",
    "MultiwfnStateIdentityError",
    "NtoPairRecord",
    "NtoPairSelection",
    "ParsedMultiwfnHoleElectron",
    "ParsedMultiwfnNto",
    "RenderedMultiwfnExcitedStateInput",
    "UnsupportedMultiwfnFormatError",
    "build_command_spec",
    "build_excited_state_command_spec",
    "discover_outputs",
    "finalize_multiwfn_hole_electron_artifact",
    "finalize_multiwfn_nto_artifact",
    "parse_multiwfn38_hole_electron_session",
    "parse_multiwfn38_hole_electron_session_file",
    "parse_multiwfn38_nto_session",
    "parse_multiwfn38_nto_session_file",
    "select_nto_pairs_for_cumulative_cutoff",
    "validate_reported_D_precision",
]
