#!/usr/bin/env python3
"""Synthetic Multiwfn executable that emits tiny public cube fixtures."""

from __future__ import annotations

import os
import subprocess
import sys
import time
from pathlib import Path


if "--version" in sys.argv:
    print("Multiwfn -- synthetic test double")
    print("Version 3.8")
    raise SystemExit(0)

commands = sys.stdin.read()
log = os.environ.get("FAKE_MULTIWFN_LOG")
if log:
    with Path(log).open("a", encoding="utf-8") as handle:
        handle.write(os.environ.get("CMW_MULTIWFN_OPERATION", "") + "\n")
        handle.write(f"threads={os.environ.get('OMP_NUM_THREADS', '')}\n")
        handle.write(f"stdin={len(commands.encode())}\n")

child_seconds = float(os.environ.get("FAKE_MULTIWFN_CHILD_SECONDS", "0"))
if child_seconds:
    child = subprocess.Popen(
        [sys.executable, "-c", f"import time; time.sleep({child_seconds})"]
    )
    child.wait()

geometry_path = Path(os.environ["CMW_SOURCE_GEOMETRY"])
lines = geometry_path.read_text(encoding="utf-8").splitlines()
atoms = [line.split() for line in lines[2:]]
numbers = {
    "H": 1,
    "C": 6,
    "N": 7,
    "O": 8,
    "F": 9,
    "S": 16,
}
angstrom_per_bohr = 0.529177210903


def cube_text(*, shifted_origin: bool = False, shifted_geometry: bool = False) -> str:
    origin = " 0.100000 0.000000 0.000000" if shifted_origin else " 0.000000 0.000000 0.000000"
    rows = [
        "synthetic cube",
        "generated by public test double",
        f"{len(atoms):5d}{origin}",
        "    2  0.500000  0.000000  0.000000",
        "    2  0.000000  0.500000  0.000000",
        "    2  0.000000  0.000000  0.500000",
    ]
    for index, fields in enumerate(atoms):
        symbol, x, y, z = fields
        bx, by, bz = (float(value) / angstrom_per_bohr for value in (x, y, z))
        if shifted_geometry and index == 0:
            bx += 0.1
        rows.append(
            f"{numbers[symbol]:5d} 0.000000 {bx: .9f} {by: .9f} {bz: .9f}"
        )
    rows.extend((" 0.0 0.1 0.2 0.3 0.4 0.5", " 0.6 0.7"))
    return "\n".join(rows) + "\n"


operation = os.environ.get("CMW_MULTIWFN_OPERATION")
filenames = {
    "FMO": ("homo.cube", "lumo.cube"),
    "ESP": ("density.cube", "esp.cube"),
    "IGMH": ("dg_inter.cub", "sl2r.cub"),
}.get(operation)
if filenames is None:
    raise SystemExit("unknown synthetic operation")
missing = os.environ.get("FAKE_MULTIWFN_MISSING", "")
malformed = os.environ.get("FAKE_MULTIWFN_MALFORMED", "")
for index, filename in enumerate(filenames):
    role = filename.split(".")[0]
    if missing in {role, filename}:
        continue
    content = (
        "malformed cube\n"
        if malformed in {role, filename}
        else cube_text(
            shifted_origin=index == 1 and os.environ.get("FAKE_MULTIWFN_MISMATCH_GRID") == "1",
            shifted_geometry=os.environ.get("FAKE_MULTIWFN_MISMATCH_GEOMETRY") == "1",
        )
    )
    Path(filename).write_text(content, encoding="utf-8")

print(f"synthetic {operation} completed")
